//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: light framework (CF/Silverlight) enabled
    
// Generated from: tmp/3.proto
namespace Spectator.Core.Model.Web.Proto
{
  [global::ProtoBuf.ProtoContract(Name=@"ProtoSnapshotsResponse")]
  public partial class ProtoSnapshotsResponse : global::ProtoBuf.IExtensible
  {
    public ProtoSnapshotsResponse() {}
    
    private readonly global::System.Collections.Generic.List<string> _StashIds = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"StashIds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> StashIds
    {
      get { return _StashIds; }
    }
  
    private readonly global::System.Collections.Generic.List<Spectator.Core.Model.Web.Proto.ProtoSnapshotsResponse.ProtoSnapshot> _Snapshots = new global::System.Collections.Generic.List<Spectator.Core.Model.Web.Proto.ProtoSnapshotsResponse.ProtoSnapshot>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Snapshots", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Spectator.Core.Model.Web.Proto.ProtoSnapshotsResponse.ProtoSnapshot> Snapshots
    {
      get { return _Snapshots; }
    }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoSnapshot")]
  public partial class ProtoSnapshot : global::ProtoBuf.IExtensible
  {
    public ProtoSnapshot() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _Source;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Source", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Source
    {
      get { return _Source; }
      set { _Source = value; }
    }
    private int _Thumbnail = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Thumbnail", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Thumbnail
    {
      get { return _Thumbnail; }
      set { _Thumbnail = value; }
    }
    private string _Title;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Title
    {
      get { return _Title; }
      set { _Title = value; }
    }
    private long _Updated;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Updated", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Updated
    {
      get { return _Updated; }
      set { _Updated = value; }
    }
    private bool _HasContent;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"HasContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool HasContent
    {
      get { return _HasContent; }
      set { _HasContent = value; }
    }
    private string _SubscriptionName;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"SubscriptionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SubscriptionName
    {
      get { return _SubscriptionName; }
      set { _SubscriptionName = value; }
    }
    private int _SubscriptionIcon = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"SubscriptionIcon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SubscriptionIcon
    {
      get { return _SubscriptionIcon; }
      set { _SubscriptionIcon = value; }
    }
    private bool _HasScreenshots;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"HasScreenshots", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool HasScreenshots
    {
      get { return _HasScreenshots; }
      set { _HasScreenshots = value; }
    }
    private bool _HasRevisions;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"HasRevisions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool HasRevisions
    {
      get { return _HasRevisions; }
      set { _HasRevisions = value; }
    }
    private int _SubscriptionId;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"SubscriptionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SubscriptionId
    {
      get { return _SubscriptionId; }
      set { _SubscriptionId = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _Images = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(12, Name=@"Images", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Images
    {
      get { return _Images; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoSubscriptionResponse")]
  public partial class ProtoSubscriptionResponse : global::ProtoBuf.IExtensible
  {
    public ProtoSubscriptionResponse() {}
    
    private readonly global::System.Collections.Generic.List<Spectator.Core.Model.Web.Proto.ProtoSubscriptionResponse.ProtoSubscription> _Subscriptions = new global::System.Collections.Generic.List<Spectator.Core.Model.Web.Proto.ProtoSubscriptionResponse.ProtoSubscription>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Subscriptions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Spectator.Core.Model.Web.Proto.ProtoSubscriptionResponse.ProtoSubscription> Subscriptions
    {
      get { return _Subscriptions; }
    }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoSubscription")]
  public partial class ProtoSubscription : global::ProtoBuf.IExtensible
  {
    public ProtoSubscription() {}
    
    private string _Title;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Title
    {
      get { return _Title; }
      set { _Title = value; }
    }
    private string _Source;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Source", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Source
    {
      get { return _Source; }
      set { _Source = value; }
    }
    private int _Id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _SubscriptionId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SubscriptionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SubscriptionId
    {
      get { return _SubscriptionId; }
      set { _SubscriptionId = value; }
    }
    private string _Group;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Group", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Group
    {
      get { return _Group; }
      set { _Group = value; }
    }
    private int _Thumbnail;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Thumbnail", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Thumbnail
    {
      get { return _Thumbnail; }
      set { _Thumbnail = value; }
    }
    private int _UnreadCount;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"UnreadCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int UnreadCount
    {
      get { return _UnreadCount; }
      set { _UnreadCount = value; }
    }
    private int _ThumbnailWidth;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"ThumbnailWidth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ThumbnailWidth
    {
      get { return _ThumbnailWidth; }
      set { _ThumbnailWidth = value; }
    }
    private int _ThumbnailHeight;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"ThumbnailHeight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ThumbnailHeight
    {
      get { return _ThumbnailHeight; }
      set { _ThumbnailHeight = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}