#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Spectator.Android.Resource", IsApplication=true)]

namespace Spectator.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int error = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int errorAuth = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int errorGeneral = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int list = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int menuFragment = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int progress = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int refresh = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int snapshotFragment = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int title = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int webview = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_profile = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_snapshots = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int item_snapshot = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int item_subscription = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
